# Generated by Django 3.1.2 on 2020-10-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longtitude', models.FloatField()),
                ('Unique_Squirrel_ID', models.CharField(max_length=100)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('', '')], default='', max_length=15)),
                ('Date', models.CharField(default='', max_length=100)),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('', '')], default='', max_length=30)),
                ('Primary_Fur', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('', '')], default='', max_length=30)),
                ('Location', models.CharField(blank=True, choices=[('Ground', 'Ground'), ('Above', 'Above'), ('', '')], default='', max_length=30)),
                ('Specific_Location', models.CharField(blank=True, max_length=100)),
                ('Running', models.BooleanField()),
                ('Chasing', models.BooleanField()),
                ('Climbing', models.BooleanField()),
                ('Eating', models.BooleanField()),
                ('Foraging', models.BooleanField()),
                ('Other_Activities', models.CharField(blank=True, max_length=100)),
                ('Kuks', models.BooleanField()),
                ('Quaas', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('Tail_Flags', models.BooleanField()),
                ('Tail_Twitches', models.BooleanField()),
                ('Approaches', models.BooleanField()),
                ('Indifferent', models.BooleanField()),
                ('Runs_From', models.BooleanField()),
            ],
        ),
    ]
