# Generated by Django 3.0.7 on 2020-10-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Approaches',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='Chasing',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='Climbing',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='Eating',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='Foraging',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='Indifferent',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='Kuks',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='Moans',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='Quaas',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='Running',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='Runs_From',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='Tail_Flags',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='Tail_Twitches',
            field=models.NullBooleanField(),
        ),
    ]
