# Generated by Django 3.1.2 on 2020-10-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_auto_20201017_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Approaches',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Chasing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Climbing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Eating',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Foraging',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Indifferent',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Kuks',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Moans',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Quaas',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Running',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Runs_From',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Tail_Flags',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Tail_Twitches',
            field=models.BooleanField(null=True),
        ),
    ]
